### ISSUE TITLE
Error - Insights with the new Frappe 15 and Erpnext 15.

### ISSUE THREAD

**Issue by girumtibebu** [frappe/insights#180]
I’ve installed Insights with the new Frappe 15 and Erpnext 15. Installation was smooth but when i try to connect to data source it’s showing error.
When I try to load the sample dataset it gets stuck on loading (the contiune buttons is disabled), it creates the local csv and sqllite files but it’s stuck. When i try to connect to erpnext it won’t contiune to the dashboard. Its throwing the error below on the console.
frappe-ui-84310e25.js:1 TypeError: M.update is not a function
at Setup-5a789eef.js:5:111
at Generator.next ()
at Setup-5a789eef.js:1:196
at new Promise ()
at C (Setup-5a789eef.js:1:16)
at a (Setup-5a789eef.js:5:50)
at Sr (frappe-ui-84310e25.js:1:15285)
at vn (frappe-ui-84310e25.js:1:15364)
at Xw (frappe-ui-84310e25.js:1:17756)
at s (Setup-5a789eef.js:1:2919)

**Comment by nextchamp-saqib** [comment]
fixed cbe5766943e1aa5761ee262d8cb117970456b173
Thanks for reporting

**Comment by girumtibebu** [comment]
Wow, thanks for the quick response
But am still facing the same issue. I pulled the develop branch, migrated rebuilt. I've checked i've the latest one but the problem persists.
